### ISSUE TITLE
Setup Dev Environment

### ISSUE THREAD

**Issue by vaibhavglokhande** [vglo/SalonWebService#1]
Setup the development environment to be followed across all microservices.

TODO:

- [x] Setup package structure.
- [x] Setup Eureka discovery server.
- [x] Setup microservice client archetype (template).
- [ ] Setup Api documentation using Swagger. Ref [link](https://dzone.com/articles/centralized-documentation-in-microservice-spring-b)
- [x] Setup microservice clients for user modules.
- [ ] Setup boilerplate code for database connection.

**Comment by agrawaly52** [comment]
Above task was completed.
